name: Biome Check & Comment (Changed Files)

on:
  push:
    branches:
      - "main"
  pull_request:

permissions:
  pull-requests: write

jobs:
  biome-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run Biome check and capture output
        id: biome_check
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "Running Biome on changed files since ${{ github.event.pull_request.base.ref }}..."
            BIOME_COMMAND="pnpm exec biome check --changed --since=${{ github.event.pull_request.base.ref }}"
          else
            echo "Running Biome on all files..."
            BIOME_COMMAND="pnpm exec biome check"
          fi
          
          BIOME_OPTIONS="--max-diagnostics=none --no-errors-on-unmatched --files-ignore-unknown=true"
          
          BIOME_OUTPUT=$($BIOME_COMMAND $BIOME_OPTIONS) || true
          COMMAND_STATUS=$?
          
          echo "output<<EOF" >> $GITHUB_OUTPUT
          echo "$BIOME_OUTPUT" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          
          if [[ $COMMAND_STATUS -ne 0 ]]; then
            echo "status=failure" >> $GITHUB_OUTPUT
          else
            echo "status=success" >> $GITHUB_OUTPUT
          fi

      - name: Post Biome results to PR
        if: github.event_name == 'pull_request'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: |
            ### 📝 Biome Check Results (Changed Files)

            <details>
            <summary>Click to expand for details</summary>

            ```text
            ${{ steps.biome_check.outputs.output }}
            ```

            </details>
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Fail workflow if Biome check failed
        if: steps.biome_check.outputs.status == 'failure'
        run: |
          echo "Biome check failed. See the comment above for the full report."
          exit 1